name: globalmaker
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - geopandas
  - shapely
  - scikit-learn
  - scipy
  - scikit-image
  - pillow
  - networkx
  - pyyaml
  - tqdm
  - pyarrow
  - pytorch::pytorch
  - pytorch::torchvision
  - huggingface_hub
  - tensorboard
  - pip:
    - tensorboard-logger
    - torch-geometric
    - torch-scatter
    - torch-sparse
